# Generated by Django 4.0.3 on 2022-08-03 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_serviceappointment_technician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='year',
        ),
        migrations.RemoveField(
            model_name='serviceappointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='serviceappointment',
            name='time',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician', to='service_rest.technician'),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='vin',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='technician',
            name='employee_number',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
