# Generated by Django 4.0.3 on 2022-08-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_remove_serviceappointment_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='finished',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
