# Generated by Django 4.0.3 on 2022-08-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_alter_serviceappointment_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
